# Generated by Django 6.0.3 on 2026-05-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_to_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
